blank_issues_enabled: true
contact_links:
  - name: 主题文档
    url: https://blog.wehaox.com/archives/typecho-butterfly.html
    about: 主题文档
    
  - name: 主题下载
    url: https://github.com/wehaox/Typecho-Butterfly/releases
    about: 主题下载
    
  - name: 静态文件
    url: https://github.com/wehaox/Typecho-Butterfly/releases/download/1.7.7/static-23.11.zip
    about: 最新的本地静态文件下载
    
  - name: 提交普通问题
    url: https://github.com/wehaox/Typecho-Butterfly/issues/new
    about: 非bug问题可以在这里提交
